# Generated by Django 3.0.2 on 2021-04-02 19:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 19, 6, 25, 335045, tzinfo=utc)),
        ),
    ]
