# Generated by Django 3.0.2 on 2021-04-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_disliked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_liked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
