# Generated by Django 3.0.2 on 2021-04-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='topic_name',
            field=models.CharField(choices=[('P', 'Politics'), ('H', 'Health'), ('S', 'Sports'), ('T', 'Tech')], max_length=2, unique=True),
        ),
    ]
