# Generated by Django 3.0.2 on 2021-04-02 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_auto_20210402_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='expiration_timestamp',
            new_name='expiry_in_seconds',
        ),
        migrations.AlterField(
            model_name='messages',
            name='creation_timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 2, 19, 27, 14, 845988, tzinfo=utc)),
        ),
    ]
