# Generated by Django 3.0.2 on 2021-04-02 19:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_auto_20210402_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='creation_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
